### ISSUE TITLE
Update the abstract avatar to have tits and a pp

### ISSUE THREAD

**Issue by fse4tfserfew4f** [jll123567/VR-Content#2]
Can you update the abstract avatar to have tits and a pp and balls. 
Attached is a reference sketch for an updated model. I blurred the pp so it's safe for work.

![image](https://github.com/jll123567/VR-Content/assets/56850840/00dc92f3-6f9d-46f1-8601-98db428822f1)

**Comment by jll123567** [comment]
maybe

**Comment by jll123567** [comment]
Fixed with commit a59c5b6
